version: "3.5"

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-books}
    ports:
      - "5432:5432"
    networks:
      - api
    restart: unless-stopped

  app:
    depends_on:
      - postgres
    container_name: api_container
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URL: ${SQLALCHEMY_DATABASE_URL:-postgresql+psycopg2://user:password@postgres:5432/books}
    ports:
      - "8000:8000"
    networks:
      - api
    restart: unless-stopped

networks:
  api:
    driver: bridge
