apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: test/api:latest
          ports:
            - containerPort: 8000
          env:
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql+psycopg2://user:password@postgres-service:5432/books"
          resources:
            limits:
              cpu: "1500m"
              memory: "1.5Gi"
            requests:
              cpu: "500m"
              memory: "0.5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 8000