apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: test/api:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRESQL_HOST
              value: "postgresql-service"
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_USER
              value: "user"
            - name: POSTGRESQL_PASSWORD
              value: "password"
            - name: POSTGRESQL_DB
              value: "books"
          resources:
            limits:
              cpu: "1500m"
              memory: "1.5Gi"
            requests:
              cpu: "500m"
              memory: "0.5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 8000